LEX_OUTPUT_DIR = "../output/lex_output"
GRAMMAR_INPUT_DIR = "../input/grammars.txt"
TEST_CODE_DIR = "../input/test_code"
TOKEN_INPUT_DIR = "../input/lex_input/test1.c"
LEX_ID="1_1"
LEX_OUTPUT_FILE = f"{LEX_OUTPUT_DIR}/lex{LEX_ID}.txt"